import type { Metadata } from "next";
import { effra } from "./font";
import "./globals.css";

export const metadata: Metadata = {
  title: "FindThread",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={effra.className}>{children}</body>
    </html>
  );
}
